version: "2.4"

services:
  mongo:
    image           : mongo:4.0.1
    container_name  : mongo
    ports           : ['27017:27017']
    network_mode    : host
    restart         : always
    mem_limit       : 400m
    environment     :
      - MONGO_DATA_DIR=/data/db/mongo
      - MONGO_LOG_DIR=/var/log/mongo
    healthcheck:
      test          : curl -s http://localhost:27017 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval      : 60s
      timeout       : 30s
      retries       : 5
    command: mongod --smallfiles --storageEngine=wiredTiger
    volumes:
      - /data/db/mongo:/data/db
      - /var/log/mongo:/var/log/mongo
